/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#d0bcff",
        "inverse-primary": "#6d3bd7",
        "primary-fixed": "#e9ddff",
        "on-primary-fixed": "#23005c",
        "on-tertiary": "#003824",
        "on-primary": "#3c0091",
        "on-tertiary-fixed": "#002113",
        "outline": "#958ea0",
        "tertiary-container": "#00a572",
        "on-surface-variant": "#cbc3d7",
        "on-primary-fixed-variant": "#5516be",
        "surface-container-low": "#1d1a26",
        "on-secondary-fixed": "#2c0051",
        "secondary-fixed": "#f0dbff",
        "primary": "#d0bcff",
        "primary-accent": "#8b5cf6",
        "primary-glow": "#a078ff",
        "on-tertiary-fixed-variant": "#005236",
        "primary-container": "#a078ff",
        "outline-variant": "#494454",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "surface-variant": "#373340",
        "on-secondary": "#490081",
        "on-tertiary-container": "#00311f",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#340080",
        "secondary-container": "#62259b",
        "on-secondary-fixed-variant": "#62259b",
        "inverse-surface": "#e7dff0",
        "tertiary-fixed": "#6ffbbe",
        "on-surface": "#e7dff0",
        "surface-container": "#211e2a",
        "tertiary": "#4edea3",
        "secondary-fixed-dim": "#ddb8ff",
        "surface": "#15121d",
        "surface-bright": "#3b3744",
        "surface-container-high": "#2c2834",
        "secondary": "#ddb8ff",
        "surface-dim": "#15121d",
        "on-secondary-container": "#d1a1ff",
        "background": "#15121d",
        "primary-fixed-dim": "#d0bcff",
        "on-background": "#e7dff0",
        "surface-container-lowest": "#100c18",
        "error-container": "#93000a",
        "inverse-on-surface": "#322e3b",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-highest": "#373340",
        "obsidian-dark": "#0B0813",
        "obsidian-card": "#1E1538",
        "obsidian-border": "#3A2868"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"]
      }
    }
  },
  plugins: []
}
